/* Auto-generated by scripts/generate-build-info.cjs. Do not edit. */

export type BuildMode = 'development' | 'production';

export type BuildInfo = {
	version: string;
	gitSha: string;
	gitDirty: boolean;
	mode: BuildMode;
	channel: string;
	buildId: string;
	builtAt: string;
};

export const BUILD_INFO: BuildInfo = {
	"version": "1.2.2",
	"gitSha": "29869be",
	"gitDirty": false,
	"mode": "production",
	"channel": "itch",
	"buildId": "20260718-213148",
	"builtAt": "2026-07-18T21:31:48.921Z"
};
