/* Auto-generated by scripts/generate-build-info.cjs. Do not edit. */

export type BuildMode = 'development' | 'production';

export type BuildInfo = {
	version: string;
	gitSha: string;
	gitDirty: boolean;
	mode: BuildMode;
	channel: string;
	buildId: string;
	builtAt: string;
};

export const BUILD_INFO: BuildInfo = {
	"version": "1.2.0",
	"gitSha": "64313a3",
	"gitDirty": true,
	"mode": "development",
	"channel": "local",
	"buildId": "20260714-195051",
	"builtAt": "2026-07-14T19:50:51.401Z"
};
